describe('Pagination', () => {
  before(() => {
    cy.visit('http://localhost:9000/cypress/pagination');
  });

  describe('Interaction', () => {
    it('Default', () => {
      cy.get('.active')
        .find('.first', '.prev')
        .should('have.class', 'disabled')
        .parents('.active')
        .find('.pagination-button')
        .contains('1')
        .should('have.class', 'selected');
    });
    it('Basic usage', () => {
      cy.get('.active')
        .find('.pagination-button')
        .contains('1')
        .should('have.class', 'selected')
        .parents('.active')
        .find('.next')
        .click()
        .get('.pagination-button')
        .contains('2')
        .should('have.class', 'selected')
        .get('.pagination-button')
        .contains('1')
        .should('have.attr', 'tabindex', '-1')
        .get('.pagination-button')
        .contains('...')
        .click()
        .parents('.active')
        .find('.pagination-button')
        .contains('7')
        .should('be.visible')
        .and('have.class', 'selected')
        .parents('.active')
        .find('.last')
        .click()
        .parents('.active')
        .find('.pagination-button')
        .contains('13')
        .should('be.visible')
        .and('have.class', 'selected')
        .parents('.active')
        .find('.last', '.next')
        .should('have.class', 'disabled')
        .parents('.active')
        .find('.prev')
        .click()
        .parents('.active')
        .find('.pagination-button')
        .contains('12')
        .should('have.class', 'selected')
        .parents('.active')
        .find('.first')
        .click()
        .parents('.active')
        .find('.pagination-button')
        .contains('1')
        .should('be.visible')
        .and('have.class', 'selected')
        .parents('.active')
        .find('.first', '.prev')
        .should('have.class', 'disabled');
    });
    it('Selecting the number of pages', () => {
      cy.get('.active')
        .find('.dropdownselect-select-icon')
        .click()
        .parents()
        .find('.suggestion-wrapper')
        .contains('.suggestion-item', '5')
        .click()
        .get('.active')
        .find('.pagination-label-info')
        .should('contain', '5')
        .get('.active')
        .find('.dropdownselect-select-icon')
        .click()
        .parents()
        .find('.suggestion-wrapper')
        .contains('.suggestion-item', '10')
        .click()
        .get('.active')
        .find('.pagination-label-info')
        .should('contain', '10')
        .get('.active')
        .find('.dropdownselect-select-icon')
        .click()
        .parents()
        .find('.suggestion-wrapper')
        .contains('.suggestion-item', '20')
        .click()
        .get('.active')
        .find('.pagination-label-info')
        .should('contain', '20')
        .get('.active')
        .find('.dropdownselect-select-icon')
        .click()
        .parents()
        .find('.suggestion-wrapper')
        .contains('.suggestion-item', '50')
        .click()
        .get('.active')
        .find('.pagination-label-info')
        .should('contain', '50');
    });
    it('Select a page by clicking', () => {
      cy.get('.active')
        .find('.pagination-button')
        .contains('1')
        .should('have.class', 'selected')
        .parents('.active')
        .find('.pagination-button')
        .contains('2')
        .click()
        .get('span.pagination-button')
        .contains('2')
        .should('have.class', 'selected')
        .parents('.active')
        .find('.pagination-button')
        .contains('1')
        .should('have.attr', 'tabindex', '-1');
    });
  });
});
